add env control

diff --git a/init.d/pony b/init.d/pony
--- a/init.d/pony
+++ b/init.d/pony
@@ -15,6 +15,10 @@ if [[ -z $2 ]]; then
   echo >&2 "Instance name required" && exit 0
 fi
 
+if [[ -z $2 ]]; then
+  echo >&2 "Instance name required" && exit 0
+fi
+
 source /etc/unicorn/$2.conf
 
 
@@ -22,7 +26,7 @@ source /etc/unicorn/$2.conf
 TIMEOUT=${TIMEOUT-60}
 APP_ROOT=$app_root
 PID=$APP_ROOT/tmp/pids/unicorn.pid
-CMD="cd $APP_ROOT; bundle exec unicorn -D -c $APP_ROOT/config/unicorn.rb -E production"
+CMD="cd $APP_ROOT; bundle exec unicorn -D -c $APP_ROOT/config/unicorn.rb -E $3"
 AS_USER=$user
 
 set -u
