oops, fix  error message

diff --git a/init.d/pony b/init.d/pony
--- a/init.d/pony
+++ b/init.d/pony
@@ -16,7 +16,7 @@ if [[ -z $2 ]]; then
 fi
 
 if [[ -z $3 ]]; then
-  echo >&2 "Instance name required" && exit 0
+  echo >&2 "Environment name required" && exit 0
 fi
 
 source /etc/unicorn/$2.conf
